name: New Release
on:
  push:
    tags:
      - v*

env:
  ENV_REPO: "tgrall-gitops/winterfest-2021-env"      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: GitHub Container Registry Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: octodemobo
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Container
        id: build_push_container
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            VERSION=${{github.ref_name}}
            REPOSITORY_NAME=${{ github.repository }}
            revision=${{ github.sha }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{github.ref_name}}


      - run : docker images

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Add TAG_NAME env property
        run:  echo "TAG_NAME=`echo ${GITHUB_REF#refs/tags/}`" >> $GITHUB_ENV
      - name: Open PR in Environment Repository for New App Release
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: "New App Release"
          token: ${{ secrets.GITOPS }}
          inputs: '{"tag_name": "${{ env.TAG_NAME }}", "app_repo": "${{ github.event.repository.name }}", "image": "ghcr.io/${{ github.repository }}:${{github.ref_name}}" }'
          ref: refs/heads/main
          repo: ${{ env.ENV_REPO }}